dependencies:
  # Some of these are not hard requirements, but attempting to avoid pip
  # installing these
  - affine
  - cartopy_offlinedata
  # only a util requirement
  - click
  - coverage
  - cython
  - defusedxml
  - fiona
  - gdal
  - geopandas
  - geos
  # templating
  - jinja2
  - matplotlib-base
  - metpy
  - metar>=1.7.0
  - mock
  - netCDF4
  # xss
  - nh3
  - numpy
  - pandas
  # webutil
  - paste
  # geoplot usage
  - pillow
  - psycopg
  # parquet format support in geopandas
  - pyarrow
  # Models
  - pydantic
  - pygrib
  - pymemcache
  # Faster shapefile reading
  - pyogrio
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mpl
  - pytest-runner
  - pytest-xdist
  - rasterstats
  # grid reprojection
  - rasterio
  # Sometimes we download stuff
  - requests
  # shrug
  - requests-mock
  # interpolation
  - scipy
  - setuptools_scm
  - shapely
  # shrug
  - sphinxcontrib-napoleon
  - sqlalchemy
  # iemre
  - xarray
