dependencies:
  # Some of these are not hard requirements, but attempting to avoid pip
  # installing these
  - affine
  # docs
  - autodoc-pydantic
  - cartopy_offlinedata
  # only a util requirement
  - click
  - coverage
  - cython
  - defusedxml
  - docutils
  - gdal
  # add_labels addition to plot()
  - geopandas>=1.2.0
  - geos
  # templating
  - jinja2
  # Need for stable tests
  - matplotlib-base>=3.11.0
  - metpy
  - metar>=1.7.0
  - mock
  - netCDF4
  - numpy
  # modern
  - pandas>=3
  # webutil
  - paste
  # geoplot usage
  - pillow
  - psycopg
  # parquet format support in geopandas
  - pyarrow
  # Models
  - pydantic>=2.11
  # docs
  - pydata-sphinx-theme
  - pygrib
  - pymemcache
  # Faster shapefile reading
  - pyogrio
  - pyproj
  - pytest
  - pytest-cov
  - pytest-mpl
  - pytest-runner
  - pytest-xdist
  - rasterstats
  # grid reprojection
  - rasterio
  # Download stuff
  - requests
  # Test requests
  - responses
  # interpolation
  - scipy
  - setuptools_scm
  - shapely
  - sphinx>=8.2
  - sqlalchemy
  # testing
  - werkzeug
  # iemre
  - xarray
