"""Stub file."""

from pyiem.models.gridnav import CartesianGridNavigation

class IEMRE(CartesianGridNavigation): ...
class IEMRE_CHINA(CartesianGridNavigation): ...
class IEMRE_EUROPE(CartesianGridNavigation): ...
class ERA5LAND(CartesianGridNavigation): ...
class ERA5LAND_CHINA(CartesianGridNavigation): ...
class ERA5LAND_EUROPE(CartesianGridNavigation): ...
class STAGE4(CartesianGridNavigation): ...
class STAGE4_PRE2002(CartesianGridNavigation): ...
class MRMS_IEMRE(CartesianGridNavigation): ...
class PRISM(CartesianGridNavigation): ...
