"""Stub file."""

from pyiem.models.gridnav import CartesianGridNavigation

class IEMRE_CONUS(CartesianGridNavigation): ...
class IEMRE_CHINA(CartesianGridNavigation): ...
class IEMRE_EUROPE(CartesianGridNavigation): ...
class IFC(CartesianGridNavigation): ...
class ERA5LAND_CONUS(CartesianGridNavigation): ...
class ERA5LAND_CHINA(CartesianGridNavigation): ...
class ERA5LAND_EUROPE(CartesianGridNavigation): ...
class STAGE4(CartesianGridNavigation): ...
class STAGE4_PRE2002(CartesianGridNavigation): ...
class MRMS_IEMRE(CartesianGridNavigation): ...
class PRISM(CartesianGridNavigation): ...
class PRISM800(CartesianGridNavigation): ...

def get_nav(
    name: str, region: str | None = "conus"
) -> CartesianGridNavigation: ...
