name: pyiem
channels:
  - scitools
  - conda-forge
dependencies:
  - python=2.7
  - sphinx>=1.3
  - matplotlib
  - numpy
  - scipy
  - Pillow
  - gdata
  - oauth2client
  - apiclient
  - urllib3
  - google-api-python-client
  - psycopg2
  - pyproj
  - python-metar
  - windrose
  - cartopy
