name: pyiem
channels:
  - scitools
  - conda-forge
dependencies:
  - python=2.7
  - sphinx>=1.3
  - numpy
  - scipy
  - gdata
  - urllib3
  - psycopg2
  - pyproj
  - cartopy
  - google-api-python-client
  - pip:
    - matplotlib
    - oauth2client
    - Pillow
    - python-metar 
    - git+https://github.com/smartsheet-platform/smartsheet-python-sdk
    - pyiem
