name: pyiem
channels:
  - scitools
  - conda-forge
dependencies:
  - python=2.7
  - sphinx>=1.3
  - numpy
  - scipy
  - gdata
  - urllib3
  - psycopg2
  - pyproj
  - cartopy
  - pip:
    - matplotlib
    - apiclient
    - oauth2client
    - google-api-python-client
    - Pillow
    - python-metar 
    - git+https://github.com/smartsheet-platform/smartsheet-python-sdk
    - git+https://github.com/akrherz/windrose.git@darylchanges
    - pyiem
